/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

// Tipos gerados pelo gltfjsx
type ActionName = 'CharacterArmature|Bite_Front' | 'CharacterArmature|Dance' | 'CharacterArmature|Death' | 'CharacterArmature|HitRecieve' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|No' | 'CharacterArmature|Walk' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Alien_Blob001_1: THREE.SkinnedMesh
    Alien_Blob001_2: THREE.SkinnedMesh
    Alien_Blob_1: THREE.SkinnedMesh
    Alien_Blob_2: THREE.SkinnedMesh
    Body: THREE.Bone
    Head: THREE.Bone
  }
  materials: {
    Eye_White: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
    Alien_Main: THREE.MeshStandardMaterial
    Alien_Secondary: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

// Tipo para as props do componente
type AlienModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function AlienModel(props: AlienModelProps) {
  const group = React.useRef<THREE.Group>(null)
  // CORRIGIDO: Caminho e tipagem
  const { scene, animations } = useGLTF('/models/Alien-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  // CORRIGIDO: Tipagem
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
        </group>
        <group name="Alien_Blob001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Alien_Blob001_1" geometry={nodes.Alien_Blob001_1.geometry} material={materials.Eye_White} skeleton={nodes.Alien_Blob001_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Alien_Blob001_2" geometry={nodes.Alien_Blob001_2.geometry} material={materials.Eye_Black} skeleton={nodes.Alien_Blob001_2.skeleton} />
        </group>
        <group name="Alien_Blob" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Alien_Blob_1" geometry={nodes.Alien_Blob_1.geometry} material={materials.Alien_Main} skeleton={nodes.Alien_Blob_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Alien_Blob_2" geometry={nodes.Alien_Blob_2.geometry} material={materials.Alien_Secondary} skeleton={nodes.Alien_Blob_2.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Alien-transformed.glb') 