/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Armabee_1: THREE.SkinnedMesh
    Armabee_2: THREE.SkinnedMesh
    Armabee_3: THREE.SkinnedMesh
    Armabee_4: THREE.SkinnedMesh
    Armabee_5: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Armabee_Main: THREE.MeshStandardMaterial
    Armabee_Secondary: THREE.MeshStandardMaterial
    Eye_White: THREE.MeshStandardMaterial
    Wings: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ArmabeeModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function ArmabeeModel(props: ArmabeeModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Armabee-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Armabee" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Armabee_1" geometry={nodes.Armabee_1.geometry} material={materials.Armabee_Main} skeleton={nodes.Armabee_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Armabee_2" geometry={nodes.Armabee_2.geometry} material={materials.Armabee_Secondary} skeleton={nodes.Armabee_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Armabee_3" geometry={nodes.Armabee_3.geometry} material={materials.Eye_White} skeleton={nodes.Armabee_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Armabee_4" geometry={nodes.Armabee_4.geometry} material={materials.Armabee_Main} skeleton={nodes.Armabee_4.skeleton} /> {/* Assumindo Eye_Black ou similar se existir */}
          <skinnedMesh castShadow receiveShadow name="Armabee_5" geometry={nodes.Armabee_5.geometry} material={materials.Wings} skeleton={nodes.Armabee_5.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Armabee-transformed.glb')