/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';


type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Duck' | 'CharacterArmature|HitReact' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|Jump_Idle' | 'CharacterArmature|Jump_Land' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Run' | 'CharacterArmature|Walk' | 'CharacterArmature|Wave' | 'CharacterArmature|Weapon' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Bunny_1: THREE.SkinnedMesh
    Bunny_2: THREE.SkinnedMesh
    Bunny_3: THREE.SkinnedMesh
    Bunny_4: THREE.SkinnedMesh
    Carrot_1: THREE.SkinnedMesh // Carrot também é SkinnedMesh
    Carrot_2: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type BunnyModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function BunnyModel(props: BunnyModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${prefix}/models/Bunny-transformed.glb`) as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Bunny" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Bunny_1" geometry={nodes.Bunny_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bunny_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Bunny_2" geometry={nodes.Bunny_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bunny_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Bunny_3" geometry={nodes.Bunny_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bunny_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Bunny_4" geometry={nodes.Bunny_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bunny_4.skeleton} />
        </group>
        {/* Carrot é parte do mesmo esqueleto/armature, então deve estar dentro do grupo que recebe as animações ou ter suas próprias */}
        <group name="Carrot" position={[0.011, 0, 0.101]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Carrot_1" geometry={nodes.Carrot_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Carrot_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Carrot_2" geometry={nodes.Carrot_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Carrot_2.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload(`${prefix}/models/Bunny-transformed.glb`)