/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Duck' | 'CharacterArmature|HitReact' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|Jump_Idle' | 'CharacterArmature|Jump_Land' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Run' | 'CharacterArmature|Walk' | 'CharacterArmature|Wave' | 'CharacterArmature|Weapon' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Dino_1: THREE.SkinnedMesh
    Dino_2: THREE.SkinnedMesh
    Dino_3: THREE.SkinnedMesh
    Dino_4: THREE.SkinnedMesh
    Dino_5: THREE.SkinnedMesh
    Dino_6: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type DinoModelProps = React.ComponentPropsWithoutRef<'group'>;

// Corrigido: Nome da função para DinoModel e export default
export default function DinoModel(props: DinoModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Dino-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Dino" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Dino_1" geometry={nodes.Dino_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dino_2" geometry={nodes.Dino_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dino_3" geometry={nodes.Dino_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dino_4" geometry={nodes.Dino_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_4.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dino_5" geometry={nodes.Dino_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_5.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dino_6" geometry={nodes.Dino_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Dino_6.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Dino-transformed.glb')