/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Dragon_1: THREE.SkinnedMesh // Note: gltfjsx pode nomear malhas de forma genérica se não houver nomes no modelo
    Dragon_2: THREE.SkinnedMesh
    Dragon_3: THREE.SkinnedMesh
    Dragon_4: THREE.SkinnedMesh
    Dragon_5: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Dragon_Main: THREE.MeshStandardMaterial
    Dragon_Secondary: THREE.MeshStandardMaterial
    Dragon_Horn: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type DragonEvolvedModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function DragonEvolvedModel(props: DragonEvolvedModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Dragon Evolved-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        {/* O nome do grupo no GLTF era "Dragon", não "Dragon_Evolved" */}
        <group name="Dragon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Dragon_1" geometry={nodes.Dragon_1.geometry} material={materials.Dragon_Main} skeleton={nodes.Dragon_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dragon_2" geometry={nodes.Dragon_2.geometry} material={materials.Dragon_Secondary} skeleton={nodes.Dragon_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dragon_3" geometry={nodes.Dragon_3.geometry} material={materials.Dragon_Horn} skeleton={nodes.Dragon_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Dragon_4" geometry={nodes.Dragon_4.geometry} material={materials.Dragon_Horn} skeleton={nodes.Dragon_4.skeleton} /> {/* Pode ser Eye_White se existir */}
          <skinnedMesh castShadow receiveShadow name="Dragon_5" geometry={nodes.Dragon_5.geometry} material={materials.Eye_Black} skeleton={nodes.Dragon_5.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Dragon Evolved-transformed.glb')