/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
// import { JSX } from 'react/jsx-runtime'; // Removido

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Ghost_1: THREE.SkinnedMesh
    Ghost_2: THREE.SkinnedMesh
    Ghost_3: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Eye_White: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
    Ghost_Main: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type GhostModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function GhostModel(props: GhostModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Ghost-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Ghost" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Ghost_1" geometry={nodes.Ghost_1.geometry} material={materials.Eye_White} skeleton={nodes.Ghost_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ghost_2" geometry={nodes.Ghost_2.geometry} material={materials.Eye_Black} skeleton={nodes.Ghost_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ghost_3" geometry={nodes.Ghost_3.geometry} material={materials.Ghost_Main} skeleton={nodes.Ghost_3.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Ghost-transformed.glb')