/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Glub_Evolved_1: THREE.SkinnedMesh
    Glub_Evolved_2: THREE.SkinnedMesh
    Glub_Evolved_3: THREE.SkinnedMesh
    Glub_Evolved_4: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Glub_Main: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
    Eye_White: THREE.MeshStandardMaterial
    Wings: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type GlubEvolvedModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function GlubEvolvedModel(props: GlubEvolvedModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Glub Evolved-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Glub_Evolved" rotation={[-Math.PI / 2, 0, 0]} scale={76}> {/* scale original era 76 */}
          <skinnedMesh castShadow receiveShadow name="Glub_Evolved_1" geometry={nodes.Glub_Evolved_1.geometry} material={materials.Glub_Main} skeleton={nodes.Glub_Evolved_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Glub_Evolved_2" geometry={nodes.Glub_Evolved_2.geometry} material={materials.Eye_Black} skeleton={nodes.Glub_Evolved_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Glub_Evolved_3" geometry={nodes.Glub_Evolved_3.geometry} material={materials.Eye_White} skeleton={nodes.Glub_Evolved_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Glub_Evolved_4" geometry={nodes.Glub_Evolved_4.geometry} material={materials.Wings} skeleton={nodes.Glub_Evolved_4.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Glub Evolved-transformed.glb')