/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

type ActionName = 'CharacterArmature|Bite_Front' | 'CharacterArmature|Dance' | 'CharacterArmature|Death' | 'CharacterArmature|HitRecieve' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|No' | 'CharacterArmature|Walk' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Mushnub_Blob_1: THREE.SkinnedMesh
    Mushnub_Blob_2: THREE.SkinnedMesh
    Mushnub_Blob_3: THREE.SkinnedMesh
    Mushnub_Blob_4: THREE.SkinnedMesh
    Body: THREE.Bone
    Head: THREE.Bone
  }
  materials: {
    MushroomKing_Secondary: THREE.MeshStandardMaterial
    MushroomKing_Main: THREE.MeshStandardMaterial
    Eye_White: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type MushnubModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function MushnubModel(props: MushnubModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${prefix}/models/Mushnub-transformed.glb`) as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
        </group>
        <group name="Mushnub_Blob" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Mushnub_Blob_1" geometry={nodes.Mushnub_Blob_1.geometry} material={materials.MushroomKing_Secondary} skeleton={nodes.Mushnub_Blob_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Blob_2" geometry={nodes.Mushnub_Blob_2.geometry} material={materials.MushroomKing_Main} skeleton={nodes.Mushnub_Blob_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Blob_3" geometry={nodes.Mushnub_Blob_3.geometry} material={materials.Eye_White} skeleton={nodes.Mushnub_Blob_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Blob_4" geometry={nodes.Mushnub_Blob_4.geometry} material={materials.Eye_Black} skeleton={nodes.Mushnub_Blob_4.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload(`${prefix}/models/Mushnub-transformed.glb`)