/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

type ActionName = 'CharacterArmature|Bite_Front' | 'CharacterArmature|Dance' | 'CharacterArmature|Death' | 'CharacterArmature|HitRecieve' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|No' | 'CharacterArmature|Walk' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Mushnub_Evolved002_1: THREE.SkinnedMesh
    Mushnub_Evolved002_2: THREE.SkinnedMesh
    Mushnub_Evolved001_1: THREE.SkinnedMesh
    Mushnub_Evolved001_2: THREE.SkinnedMesh
    Mushnub_Evolved_1: THREE.SkinnedMesh
    Mushnub_Evolved_2: THREE.SkinnedMesh
    Mushnub_Evolved_3: THREE.SkinnedMesh
    Mushnub_Evolved_4: THREE.SkinnedMesh
    Body: THREE.Bone
    Head: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type MushnubEvolvedModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function MushnubEvolvedModel(props: MushnubEvolvedModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${prefix}/models/Mushnub Evolved-transformed.glb`) as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
        </group>
        <group name="Mushnub_Evolved002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved002_1" geometry={nodes.Mushnub_Evolved002_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved002_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved002_2" geometry={nodes.Mushnub_Evolved002_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved002_2.skeleton} />
        </group>
        <group name="Mushnub_Evolved001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved001_1" geometry={nodes.Mushnub_Evolved001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved001_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved001_2" geometry={nodes.Mushnub_Evolved001_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved001_2.skeleton} />
        </group>
        <group name="Mushnub_Evolved" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved_1" geometry={nodes.Mushnub_Evolved_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved_2" geometry={nodes.Mushnub_Evolved_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved_3" geometry={nodes.Mushnub_Evolved_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Mushnub_Evolved_4" geometry={nodes.Mushnub_Evolved_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Mushnub_Evolved_4.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload(`${prefix}/models/Mushnub Evolved-transformed.glb`)