/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Duck' | 'CharacterArmature|HitReact' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|Jump_Idle' | 'CharacterArmature|Jump_Land' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Run' | 'CharacterArmature|Walk' | 'CharacterArmature|Wave' | 'CharacterArmature|Weapon' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Ninja_1: THREE.SkinnedMesh
    Ninja_2: THREE.SkinnedMesh
    Ninja_3: THREE.SkinnedMesh
    Ninja_4: THREE.SkinnedMesh
    Ninja_5: THREE.SkinnedMesh
    Ninja_6: THREE.SkinnedMesh
    Ninja_7: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type NinjaxGymeDpfTuModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function NinjaxGymeDpfTuModel(props: NinjaxGymeDpfTuModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${prefix}/models/Ninja-xGymeDpfTu-transformed.glb`) as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Ninja" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Ninja_1" geometry={nodes.Ninja_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_2" geometry={nodes.Ninja_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_3" geometry={nodes.Ninja_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_4" geometry={nodes.Ninja_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_4.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_5" geometry={nodes.Ninja_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_5.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_6" geometry={nodes.Ninja_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_6.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Ninja_7" geometry={nodes.Ninja_7.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ninja_7.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload(`${prefix}/models/Ninja-xGymeDpfTu-transformed.glb`) 