/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Squidle002_1: THREE.SkinnedMesh
    Squidle002_2: THREE.SkinnedMesh
    Squidle002_3: THREE.SkinnedMesh
    Squidle002_4: THREE.SkinnedMesh
    Squidle002_5: THREE.SkinnedMesh
    Squidle002_6: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type SquidleModelProps = React.ComponentPropsWithoutRef<'group'>;

export default function SquidleModel(props: SquidleModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${prefix}/models/Squidle-transformed.glb`) as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Squidle002" rotation={[-Math.PI / 2, 0, 0]} scale={76}> {/* scale original */}
          <skinnedMesh castShadow receiveShadow name="Squidle002_1" geometry={nodes.Squidle002_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Squidle002_2" geometry={nodes.Squidle002_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Squidle002_3" geometry={nodes.Squidle002_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Squidle002_4" geometry={nodes.Squidle002_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_4.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Squidle002_5" geometry={nodes.Squidle002_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_5.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Squidle002_6" geometry={nodes.Squidle002_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Squidle002_6.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload(`${prefix}/models/Squidle-transformed.glb`)