/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Fast_Flying' | 'CharacterArmature|Flying_Idle' | 'CharacterArmature|Headbutt' | 'CharacterArmature|HitReact' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Tribal_Flying_1: THREE.SkinnedMesh
    Tribal_Flying_2: THREE.SkinnedMesh
    Tribal_Flying_3: THREE.SkinnedMesh
    Tribal_Flying_4: THREE.SkinnedMesh
    Tribal_Flying_5: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type TribalModelProps = React.ComponentPropsWithoutRef<'group'>;

// Corrigido: Nome da função para TribalModel e export default
export default function TribalModel(props: TribalModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/Tribal-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Flying_Idle') || name.includes('Idle')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <group name="Tribal_Flying" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Tribal_Flying_1" geometry={nodes.Tribal_Flying_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Tribal_Flying_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Tribal_Flying_2" geometry={nodes.Tribal_Flying_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Tribal_Flying_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Tribal_Flying_3" geometry={nodes.Tribal_Flying_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Tribal_Flying_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Tribal_Flying_4" geometry={nodes.Tribal_Flying_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Tribal_Flying_4.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Tribal_Flying_5" geometry={nodes.Tribal_Flying_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Tribal_Flying_5.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Tribal-transformed.glb')