/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
// import { JSX } from 'react/jsx-runtime'; // Removido

type ActionName = 'CharacterArmature|Bite_Front' | 'CharacterArmature|Dance' | 'CharacterArmature|Death' | 'CharacterArmature|HitRecieve' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|No' | 'CharacterArmature|Walk' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip { name: ActionName }

type GLTFResult = GLTF & {
  nodes: {
    Yeti_Blob001_1: THREE.SkinnedMesh
    Yeti_Blob001_2: THREE.SkinnedMesh
    Yeti_Blob001_3: THREE.SkinnedMesh
    Yeti_Blob001_4: THREE.SkinnedMesh
    Yeti_Blob001_5: THREE.SkinnedMesh
    Yeti_Blob001_6: THREE.SkinnedMesh
    Body: THREE.Bone
    Head: THREE.Bone
  }
  materials: { PaletteMaterial001: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

type YetiModelProps = React.ComponentPropsWithoutRef<'group'>;

// Corrigido: Nome da função para YetiModel e export default
export default function YetiModel(props: YetiModelProps) {
  const group = React.useRef<THREE.Group>(null)
  // Assumindo que Yeti-ceRHrn8HHE.glb foi renomeado ou que o -transformed é Yeti-transformed.glb
  const { scene, animations } = useGLTF('/models/Yeti-transformed.glb') as unknown as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    const actionToPlay = names.find(name => name.includes('Idle') || name.includes('Walk')) || names[0];
    if (actionToPlay && actions[actionToPlay]) {
      actions[actionToPlay]?.reset().fadeIn(0.5).play();
      return () => { actions[actionToPlay]?.fadeOut(0.5); };
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
        </group>
        <group name="Yeti_Blob001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_1" geometry={nodes.Yeti_Blob001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_1.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_2" geometry={nodes.Yeti_Blob001_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_2.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_3" geometry={nodes.Yeti_Blob001_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_3.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_4" geometry={nodes.Yeti_Blob001_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_4.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_5" geometry={nodes.Yeti_Blob001_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_5.skeleton} />
          <skinnedMesh castShadow receiveShadow name="Yeti_Blob001_6" geometry={nodes.Yeti_Blob001_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Yeti_Blob001_6.skeleton} />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/Yeti-transformed.glb')